apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-env
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: auth-env
    creationPolicy: Owner
  data:
    - secretKey: BETTER_AUTH_SECRET
      remoteRef:
        key: {{ .Values.onepassword.appItem }}
        property: BETTER_AUTH_SECRET
    - secretKey: SECRET_ENCRYPTION_KEY
      remoteRef:
        key: {{ .Values.onepassword.appItem }}
        property: SECRET_ENCRYPTION_KEY
    - secretKey: AUTH_PROJECTS
      remoteRef:
        key: {{ .Values.onepassword.appItem }}
        property: AUTH_PROJECTS
    {{- if .Values.objectStorage.enabled }}
    - secretKey: AUTH_STORAGE_ACCESS_KEY_ID
      remoteRef:
        key: {{ .Values.onepassword.appItem }}
        property: AUTH_STORAGE_ACCESS_KEY_ID
    - secretKey: AUTH_STORAGE_SECRET_ACCESS_KEY
      remoteRef:
        key: {{ .Values.onepassword.appItem }}
        property: AUTH_STORAGE_SECRET_ACCESS_KEY
    {{- end }}
