apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth.fullname" . }}
  labels:
    {{- include "auth.componentLabels" (dict "root" . "component" "router") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "auth.componentSelectorLabels" (dict "root" . "component" "router") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.router.service.port }}
      targetPort: http
