export enum ErrorCode {
  AdminNotConfigured = "admin_not_configured",
  ForbiddenOrigin = "forbidden_origin",
  InvalidBenefitKey = "invalid_benefit_key",
  InvalidBody = "invalid_body",
  InvalidCode = "invalid_code",
  InvalidPkceChallenge = "invalid_pkce_challenge",
  InvalidRedirectUri = "invalid_redirect_uri",
  InvalidStorageSettings = "invalid_storage_settings",
  InternalServerError = "internal_server_error",
  MissingClientId = "missing_client_id",
  NotFound = "not_found",
  RateLimited = "rate_limited",
  RateLimitUnavailable = "rate_limit_unavailable",
  SystemProjectLocked = "system_project_locked",
  Unauthorized = "unauthorized",
  UnknownProject = "unknown_project",
  UnknownProvider = "unknown_provider",
  UnknownReservation = "unknown_reservation"
}
